export const INITIALIZE_APP = 'INITIALIZE_APP'
export const SET_CONFIG = 'SET_CONFIG'
export const FETCH_TASKS = 'FETCH_TASKS'
export const CREATE_TASKS = 'CREATE_TASKS'
export const UPDATE_TASKS = 'UPDATE_TASKS'
export const SET_TASKS = 'SET_TASKS'
export const DELETE_TASKS = 'DELETE_TASKS'
